### ISSUE TITLE
Fix autonym for Choctaw

### ISSUE THREAD

**Issue by nikkiwd** [wikimedia/language-data#295]
The autonym for Choctaw is "Chahta" (= Choctaw) or "Chahta anumpa" (= Choctaw language)

See https://choctawschool.com/media/369055/New%20Choctaw%20Dictionary.pdf, https://choctawschool.com/lesson-of-the-day/peopleperson/person-choctaw-teacher.aspx, https://choctawschool.com/lesson-of-the-day/choctaw/chahta-anumpa-ya-the-choctaw-language.aspx

**Comment by amire80** [comment]
Fixed in 894bcff1973b34ee2bf4336e5be1e6492501cb5f.
