### ISSUE TITLE
Update Moroccan Arabic language

### ISSUE THREAD

**Issue by MarcoAurelioWM** [wikimedia/language-data#74]
See downstream task at [T237672](https://phabricator.wikimedia.org/T237672).

**Comment by MarcoAurelioWM** [comment]
Note from README.md: after adding a language to `data/langdb.yaml`, run `php ulsdata2json.php` in the `data/` directory to generate the `language-data.json` file. **Don't edit** `language-data.json` manually.

**Comment by Nikerabbit** [comment]
Assuming resolved. Downstream task is marked as resolved.
